### ISSUE TITLE
Setup CSS framework

### ISSUE THREAD

**Issue by Gerald12344** [Edulink-2-0/Edulonk#2]
I recon Styled Components + Mantine (thoughts)?

**Comment by jw2476** [comment]
Yea mantine sounds good, haven't looked at styled components but I will in a minute. What about tailwind?

**Comment by jw2476** [comment]
Yea mantine sounds good, haven't looked at styled components but I will in a minute. What about tailwind?

**Comment by Gerald12344** [comment]
Added Matine, bump if u still want tailwind
